# Generated by Django 2.2.5 on 2019-10-05 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='title',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='updated',
        ),
    ]
