# Generated by Django 2.2.5 on 2019-09-02 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_app', '0002_remove_urlshortener_long_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlshortener',
            name='long_url',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
