# Generated by Django 2.2.5 on 2019-09-03 21:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('url_app', '0004_clickdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clickdata',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
