# Generated by Django 2.2.5 on 2019-09-03 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_app', '0005_auto_20190903_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clickdata',
            name='url',
            field=models.CharField(max_length=6),
        ),
    ]
