# Generated by Django 2.2.5 on 2019-09-03 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url_app', '0006_auto_20190903_2145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clickdata',
            old_name='url',
            new_name='url_code',
        ),
    ]
