# Generated by Django 2.2.5 on 2019-09-03 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_app', '0007_auto_20190903_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlshortener',
            name='clicks',
            field=models.IntegerField(default=0),
        ),
    ]
