# Generated by Django 2.2.5 on 2019-09-04 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('url_app', '0008_urlshortener_clicks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clickdata',
            name='url_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='url_app.UrlShortener'),
        ),
    ]
