# Generated by Django 2.2.5 on 2019-09-04 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url_app', '0009_auto_20190904_1828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clickdata',
            old_name='url_code',
            new_name='url',
        ),
    ]
