# Generated by Django 2.2.4 on 2019-08-30 19:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_app', '0002_remove_groceryitem_completed_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceryitem',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 30, 19, 54, 40, 655295, tzinfo=utc), verbose_name='date created'),
        ),
    ]
