# Generated by Django 2.2.4 on 2019-09-03 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroceryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemText', models.CharField(max_length=200)),
                ('itemCount', models.IntegerField()),
                ('createdDate', models.DateTimeField()),
                ('completedDate', models.DateTimeField()),
            ],
        ),
    ]
