# Generated by Django 2.2.4 on 2019-09-09 18:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_auto_20190909_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceryitem',
            name='completedDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 9, 18, 48, 50, 63057, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='groceryitem',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 9, 18, 48, 50, 63057, tzinfo=utc)),
        ),
    ]
