# Generated by Django 2.2.5 on 2019-09-09 19:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longURL', models.CharField(max_length=500)),
                ('urlcode', models.CharField(max_length=6)),
                ('shortURL', models.CharField(max_length=20)),
                ('createdTime', models.DateTimeField(default=datetime.datetime(2019, 9, 9, 19, 14, 1, 452380, tzinfo=utc))),
            ],
        ),
    ]
