# Generated by Django 2.2.5 on 2019-09-09 21:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='createdTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 9, 21, 36, 21, 287004, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='url',
            name='shortURL',
            field=models.CharField(default='', max_length=20),
        ),
    ]
