# Generated by Django 2.2.5 on 2019-09-09 21:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_auto_20190909_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='createdTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 9, 21, 42, 39, 738473, tzinfo=utc)),
        ),
    ]
