# Generated by Django 2.2.5 on 2019-09-05 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groceryList', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='grocerylist',
            new_name='GroceryItem',
        ),
    ]
