# Generated by Django 2.2.5 on 2019-09-10 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_auto_20190910_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='facebook',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='cart',
            name='instagram',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='cart',
            name='twitter',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
