# Generated by Django 2.2.5 on 2019-09-10 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_auto_20190910_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
