# Generated by Django 2.2.4 on 2019-08-30 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_text', models.CharField(max_length=30)),
                ('is_complete', models.BooleanField(default=False, verbose_name='complete')),
            ],
        ),
    ]
