# Generated by Django 2.2.4 on 2019-09-03 19:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 3, 19, 13, 1, 453137, tzinfo=utc), verbose_name='created_date'),
            preserve_default=False,
        ),
    ]
