# Generated by Django 2.2.5 on 2019-09-05 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body',
            field=models.CharField(default='hi', max_length=10000),
            preserve_default=False,
        ),
    ]
