# Generated by Django 2.2.5 on 2019-10-02 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chirps', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chirp',
            old_name='chirpAuth',
            new_name='username',
        ),
    ]
